from tkinter import *
gui=Tk()
gui.configure(background="light green")
gui.title("List of Computer Courses")
gui.geometry("300x200")
Lb1=Listbox(gui,bg="green",fg="white",bd=1,activestyle="dotbox")
label=Label(gui,text="Computer Science Course List").pack(fill="both")
Lb1.insert(1,'Computer Networking')
Lb1.insert(2,"Information Science")
Lb1.insert(3,"Networking")
Lb1.insert(4,"Operating Systems")
Lb1.insert(5,"Artificial Intelligence")
Lb1.insert(6,"Information Technology")
Lb1.insert(7,"Information Security")
Lb1.insert(8,"Cyber Security")
Lb1.pack()
gui.mainloop()