x=c(2,3,4,5,8,8)
y=c(9,10,11,12,8,8)
print("Original data frame")
xy=data.frame(x, y)
print(xy)
print("Duplicated elements of the data frame are :")
print(duplicated(xy))
print("Unique elements of the data frame are :")
print(unique(xy))